version: '3'

networks:
  consul-network:
    driver: bridge
    external: false

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    domainname: service.consul
    ports:
      - 5432:5432
    environment:
      SERVICE_5432_NAME: postgres
      SERVICE_5432_CHECK_TCP: "true"
      SERVICE_5432_CHECK_INTERVAL: 30s
      SERVICE_5432_CHECK_TIMEOUT: 5s
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql/init/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - consul-network
    restart: unless-stopped

  shop:
    image: arina/shop:master
    container_name: shop
    hostname: shop
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_started
    networks:
      - consul-network
    restart: unless-stopped


